name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # triggers on both merges and direct pushes to master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: test  # Run only if tests pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Generate Docker tag
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          SHORT_SHA="${GITHUB_SHA::7}"
          VERSION_TAG="${BRANCH}-${SHORT_SHA}"
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
          echo "Using tag: $VERSION_TAG"

      - name: Print active account
        run: |
          gcloud auth list

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/chat-reader-repo/chat-reader:$VERSION_TAG .

      - name: Push Docker image
        run: |
          docker push ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/chat-reader-repo/chat-reader:$VERSION_TAG

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy your-service \
            --image ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/chat-reader-repo/chat-reader:$VERSION_TAG \
            --region ${{ vars.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated
