name: PR Test (merged with master)

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run Tests on Merged Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout merged code
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest